### ISSUE TITLE
[BUG] Max image dimensions alert shown twice

### ISSUE THREAD

**Issue by Bubba83** [Olliebrown/DOGProtoTesting#10]
**Describe the bug**
When I upload an image that exceeds the max dimensions, I see the alert that tells me so twice, after I hit okay on the first alert.

**To Reproduce**
1. On recipe generator
2. Upload an image that's larger than both width and height max dimension

**Expected behavior**
See one alert that says it's bigger than max dimensions

**Desktop (please complete the following information):**
- Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Browser Version: 106.0.5249.119

**Comment by Olliebrown** [comment]
This was a tricky one but I think I figured out a way to avoid it.  Thanks for submitting!
