### ISSUE TITLE
[FEATURE] Allow to edit saved recipes

### ISSUE THREAD

**Issue by ThomasEverding** [Olliebrown/DOGProtoTesting#14]
When I design some recipes, I might want to do some edits on the later on (change the region, ...). I can do that for the last / currently active recipe but not for the previous ones. I would have to re-create them. 

Possible solution:
When hovering a saved recipe, there could be an edit-button (like 'hide in flights', ...). this button would just copy the saved recipe into the edit area.
When saving the recipe, you would create a new revised instance of the recipe. An overwrite-option would be nice but is not mandatory.

**Comment by Olliebrown** [comment]
Thanks for mentioning this!  I actually had intended to support this.  I've added some things that will make this possible now:

- Among the saved recipes one can be 'Active'
- When you have an active recipe, there are two save options: Save Recipe (which updates the active one) and Save NEW Recipe (which will make a new one instead)
- You can also clear the active recipe to avoid changing it unintentionally
- Presently, when you save a new recipe it automatically becomes active (but this can be changed if it is confusing)

Feel free to give the new version a try and see if it works as you expect.

Note: @paverson might want to read the above.

**Comment by ThomasEverding** [comment]
It works nicely, thanks!
I have just one thing: the 'clear selected' button does not clear the selected recipe but removes the selection and clears the active recipe. The selected recipe stays unchanged.
I would place the clear button in the edit area above and just name it 'clear' or 'reset recipe'. The action should stay the same:  un-select the recipe and set the active recipe to a blank one.
