### ISSUE TITLE
Spirit backgrounds on custom Taste Flight

### ISSUE THREAD

**Issue by rwoods9** [Olliebrown/DOGProtoTesting#8]
On the actual taste flights, the 2nd, 4th and 6th spirits have a light grey background so you can distinguish their row from the spirits above/below them where the background is white. The custom flights don't do that, but this may be something we live with. Looks like some spirits have the white background and some have the light grey, and that doesn't change.

**Comment by Olliebrown** [comment]
This should be fixed now in the latest version.  I will confirm before I close.

**Comment by Olliebrown** [comment]
It is still wrong in the PDF so I will leave this open until that is addressed.

**Comment by Olliebrown** [comment]
Fixed now.  Had to switch to using a table with filled cells but that did the trick.
